spring:
  datasource:
    username: admin
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3305/dataStore
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 121446366474-5rad0g6md3j3jaans85chl15haoe94j9.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

server:
  port: 8000