INSERT INTO dataStore.category (name_en,behavior_th,behavior_en,name_th) VALUES
	 ('Bull','มุ่งมั่น กล้าทำ รวดเร็ว, ตรงไปตรงมา, รักพวกพ้อง, รักความยุติธรรม, ชัดเจน เป็นรูปธรรม, กล้าได้กล้าเสีย, เน้นผลลัพธ์, แรง กัดไม่ปล่อย, แก้ปัญหาเฉพาะหน้าเก่ง, จริงใจ','determined dare to do fast, straightforward,love friends, love justice, clear Concrete, enterprising, results-oriented, strong does not let go, good at solving immediate problems, sincere','กระทิง'),
	 ('Rat','ยอม ประนีประนอม, หล่อเลี้ยง อ่อนโยน, ใส่ใจความรู้สึกของผู้อื่น, เน้นความสัมพันธ์, ไม่ชอบความขัดแย้ง, เก็บความรู้สึก, เป็นมิตร, บริการ ดูแลความเป็นอยู่, เสียสละ','compromise, nurture gentle, attentive to other people''s feelings, relationship-oriented, dislikes conflict, introverted, friendly, service taking care of living, sacrificing','หนู'),
	 ('Bear','มีแบบแผน, เป็นระเบียบ เป๊ะ, ละเอียดรอบคอบ, เป็นขั้นเป็นตอน, มีมาตรฐาน, ลงลึก เจ้าหลักการ, ตรรกะ เหตุผล, ไม่เชื่ออะไรง่ายๆ, ช้าแต่ชัวร์, เน้นความแน่นอน','structured, organized Accurate, detailed, meticulous, step-by-step, standardized, deep master, logic Reason, don''t believe anything easily, slow but sure, focus on certainty','หมี'),
	 ('Falcon','มีวิสัยทัศน์ เห็นอนาคต, ความคิดสร้างสรรค์, มองภาพรวม, คิดนอกกรอบ, เจ้า โปรเจก, คิดเชื่อมโยง, ขี้เบื่อ ไม่ชอบทำอะไรช้ำ, แค่คิดก็สำเร็จแล้ว, โฉบเฉี่ยว รักอิสระ, เรียนรู้ไว ผ่านการฟัง ดูภาพ','visionary see the future, creativity, big picture, think outside the box, you project, linked thinking, boredom I don''t like to do anything bruised, just think about it and it''s done, sleek love freedom, learn quickly through listening and looking at pictures','อินทรี');

INSERT INTO dataStore.choices (name_th,name_en,category_id) VALUES
	 ('ชอบลงมือทำ','Doer',1),
	 ('ตรงไปตรงมา','Direct',1),
	 ('ผู้นำในวิกถติ','Leader in crisis',1),
	 ('กล้าชน','Confronting',1),
	 ('กล้าได้ กล้าเสีย','Risk-taking',1),
	 ('รักความยุติธรรม','Justice',1),
	 ('มุ่งมั่น','Willful',1),
	 ('แรง','Fierce',1),
	 ('ดุดัน','Hot-tempered',1),
	 ('เร็ว','Speed',1),
	 ('กล้าตัดสินใจ','Decisive',1),
	 ('ปกป้องพวกพ้อง','Protective',1),
	 ('เรียนรู้ผ่านการปฏิบัติ','Learning by doing',1),
	 ('มั่นใจในตัวเอง','Confident',1),
	 ('โผงผาง','Outspoken',1),
	 ('มุ่งเป้า','Focus',1),
	 ('นักรบ','Warrior',1),
	 ('ใจร้อน','Hotheaded',1),
	 ('เปีดเผย','Expressive',1),
	 ('เน้นผลลัพร์','Result-oriented',1),
	 ('กัดไม่ปล่อย','Perseverance',1),
	 ('ใจอ่อน','Soft hearted',2),
	 ('รักความสามัคคี','Harmony',2),
	 ('รับฟัง','Listening',2),
	 ('ไม่ชอบความขัดแย้ง','Avoid conflict',2),
	 ('ผู้ให้','Giver',2),
	 ('เก็บความรู้สืก','Repressive',2),
	 ('อ่อนโยน','Tender',2),
	 ('ขี้สงสาร','Sympathy',2),
	 ('เน้นความสัมพันร์','Relationship-oriented',2),
	 ('ผู้ประสาน','Coordinator',2),
	 ('ห่วงใยผู้อื่น','Caring',2),
	 ('ใส่ใจผู้คน','People-oriented',2),
	 ('ขี้เกรงใจ','Overmodest',2),
	 ('ยอมตาม','Compliant',2),
	 ('ประนีประนอม','Compromise',2),
	 ('ไม่ปะฏิเสร','difficult to say no',2),
	 ('ใจเย็น','Calm',2),
	 ('เสียสละ','Sacrifice',2),
	 ('เห็นอกเห็นใจผู้อื่น','Empathy',2),
	 ('สนับสนุน','Supportive',2),
	 ('พร้อมตอบรับ','Responsive',2),
	 ('มีพื้นที่ส่วนตัว','Private',3),
	 ('ใช้เหตุผล','Logic',3),
	 ('มีวินัย','Discipline',3),
	 ('ชอบความถูกต้อง','righteousness',3),
	 ('ละเอียด','Detailed',3),
	 ('ควบคุมตัวเอง','Saelf-control',3),
	 ('เน้นข้อมูน','Data',3),
	 ('อยู่กับงานช้ำๆได้','Comfortable With Routine works',3),
	 ('รอบคอบ','Prudent',3),
	 ('รู้ลึก รู้จิง','Specialize',3),
	 ('นักสะสม','Collector',3),
	 ('เน้นระบบ','Systemic',3),
	 ('รักษากติกา','Rules keeper',3),
	 ('มีขั้นตอน','Steps & Processes',3),
	 ('มีระเบียบ','Order',3),
	 ('ชอบความสมบูรณ์แบบ','Perfectionist',3),
	 ('นักวางแผน','Planner',3),
	 ('สม่ำสมอ','Consistency',3),
	 ('นิ่ง','Static',3),
	 ('วิเคราะห์','Analytical',3),
	 ('ชอบความแน่นอน','Certainty',3),
	 ('นอกกรอบ','Out of a box',4),
	 ('สร้างสรรค์','Creative',4),
	 ('รักการผจญภัย','Adventurous',4),
	 ('มองหาความเป็นไปได้ใหม่ๆ','Looking for new things',4),
	 ('ชอบทดลอง','Experimental',4),
	 ('มองภาพกว้าง','Overview perspective',4),
	 ('สนุกกับแนวคิดใหม่ๆ','Ideation',4),
	 ('สังเกดการณ์','Observe',4),
	 ('นักฝัน','Dreamer',4),
	 ('เจ้าโปรเจค','Projects initiator',4),
	 ('ยืดยุ่น','Flexible',4),
	 ('รักการเรียนรู้','Love of learning',4),
	 ('ฟุ้งช่าน','Distracted',4),
	 ('พลิกแพลง','Adaptive',4),
	 ('คิดชับช้อน','Complex thinking',4),
	 ('พร้อมเปลี่ยนแปลง','Ready to change',4),
	 ('มองการณ์ไกล','Visionary',4),
	 ('เบื่อง่าย','Boredom',4),
	 ('เชื่อมโยง','Associative',4),
	 ('นักคิด','Thinker',4),
	 ('นักกลยุภร์','Strategist',4);
